services:
  web:
    # Override the command to keep the container running for development.
    # VS Code attaches and runs commands interactively.
    command: sleep infinity

    build:
      args:
        SKIP_BUNDLE_INSTALL: true

    volumes:
      - bundle_cache:/app/vendor/bundle
