:host: "<%= ENV['LDAP_HOST'] %>"
:port: <%= ENV['LDAP_PORT'] %>
:encryption: :simple_tls
:base: "<%= ENV['LDAP_BASE'] %>"
:auth:
  :method: :simple
  :username: "<%= ENV['LDAP_USERNAME'] %>"
  :password: "<%= ENV['LDAP_PASSWORD'] %>"
