default: &default
  secret_key_base: "<%= ENV['RAILS_SECRET'] %>"
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>

development: *default
test: *default
remotedev: *default
staging: *default
production: *default