name: CI

on:
  push:
    branches: [develop, main, master, feature/add-ci]
  pull_request:
    branches: [develop, main, master]

  # Allows workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      LDAP_HOST: ${{ secrets.LDAP_HOST }}
      LDAP_BASE: ${{ secrets.LDAP_BASE }}
      LDAP_USERNAME: ${{ secrets.LDAP_USERNAME }}
      LDAP_PASSWORD: ${{ secrets.LDAP_PASSWORD }}
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - name: Verify mysql connection
        run: |
          mysql --host ${{ ENV.DB_HOST }} --port ${{ ENV.DB_PORT }} -u${{ ENV.DB_USERNAME}} -p${{ ENV.DB_PASSWORD }} -e "SHOW DATABASES"
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Setup config files for CI
        run: |
          cp config/ldap_ci.yml config/ldap.yml
      - name: Setup Database
        run: |
          cp config/database_ci.yml config/database.yml
          ./bin/rails db:create
          ./bin/rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec
        env:
          RAILS_ENV: development
